#!/bin/bash
# Make a gnirehtet release.
#
# Put your keystore properties into ~/.gradle/gradle.properties
# (check app/build.gradle)

set -e # fail on error

GRADLE=${GRADLE:-./gradlew} # set value ./gradlew if not set
DIST=dist
TARGET_DIR_JAVA=gnirehtet-java

version=$(git describe --tags --always)
TARGET_JAVA="$TARGET_DIR_JAVA-$version".zip

"$GRADLE" checkAll releaseAll

rm -rf "$DIST"

mkdir -p "$DIST/$TARGET_DIR_JAVA"
cp app/build/outputs/apk/release/gnirehtet-release.apk "$DIST/$TARGET_DIR_JAVA"/gnirehtet.apk

cp relay-java/build/libs/gnirehtet.jar \
   relay-java/scripts/README.txt \
   relay-java/scripts/gnirehtet \
   relay-java/scripts/gnirehtet.cmd \
   relay-java/scripts/gnirehtet-get-adb.cmd \
   relay-java/scripts/gnirehtet-launcher.cmd \
   relay-java/scripts/gnirehtet-repair.cmd \
   relay-java/scripts/gnirehtet-run.cmd \
   "$DIST/$TARGET_DIR_JAVA"/

cd "$DIST"
zip -r "$TARGET_JAVA" "$TARGET_DIR_JAVA"
sha256sum "$TARGET_JAVA" > SHA256SUMS.txt
